wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.2
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685800345.722035
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.10
      5: 0.15.2
      8:
      - 5
input:
  desc: null
  value: processed_data.csv:latest
test_size:
  desc: null
  value: 0.2
