main:
  project_name: project-FootballPredict
  experiment_name: development
  steps: all
directories:
  input_folder_path: raw_data
  output_folder_path: processed_data
data_check:
  kl_threshold: 0.2
data_segregation:
  test_size: 0.2
modeling:
  # Fraction of data to use for test (the remaining will be used for train and validation)
  test_size: 0.2
  # Fraction of remaining data to use for validation
  val_size: 0.2
  #nfold: 3
  xgboost:
    n_estimators: 30
    max_depth: 15
    max_leaves: 10
    max_bin: 10
    eta: 0.3
    gamma: 0
    min_child_weight: 1
    n_jobs: -1
