main:
  project_name: project-FootballPredict
  experiment_name: development
  steps: all
directories:
  input_folder_path: raw_data
  output_folder_path: processed_data
data_check:
  kl_threshold: 0.2
data_segregation:
  # Fraction of data to use for test (the remaining will be used for train and validation)
  test_size: 0.2
modeling:
  # Fraction of remaining data to use for validation
  val_size: 0.2
  linearRegression:
    fit_intercept: True
    copy_X: True
    normalize: True
    positive: False
