name: training_validation
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.1
  - pip=22.0.4
  - mlflow=1.23.0
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - numpy=1.22.3
  - pillow

  - pip:
      - wandb
      - xgboost==1.7.5
