name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.3.1
  - notebook
  - seaborn=0.11.2
  - pandas=1.4.1
  - pip=22.0.4
  - pyarrow=2.0
  - pip:
      - wandb
      - jinja2==3.0.3