# Generated by Selenium IDE
import time
import csv
import os.path
import json
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options

# Setup chrome options
chrome_options = Options()
chrome_options.add_argument("--headless")  # Ensure GUI is off
chrome_options.add_argument("--no-sandbox")


homedir = os.path.expanduser("~")
webdriver_service = Service(f"{homedir}/chromedriver/stable/chromedriver")

# Choose Chrome Browser
driver = webdriver.Chrome(service=webdriver_service, options=chrome_options)

driver.get("https://alyga.lt/rezultatai/1")

one = driver.find_element(
    By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(1)").text
two = driver.find_element(
    By.CSS_SELECTOR, "tr:nth-child(2) > .tr:nth-child(3)").text
three = driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .result").text
four = driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .tl").text
five = driver.find_element(
    By.CSS_SELECTOR, "tr:nth-child(2) > .tr:nth-child(6)").text
driver.close()

with open('test.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow([])
