wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683662603.798336
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.10.10
      5: 0.15.1
      8:
      - 5
input_artifact:
  desc: null
  value: raw_data.csv:latest
output_artifact:
  desc: null
  value: processed_data.csv
output_type:
  desc: null
  value: processed_data
output_description:
  desc: null
  value: Merged and cleaned data
