wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685808266.250382
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.10.11
      5: 0.15.3
      8:
      - 5
mlflow_model:
  desc: null
  value: model_export:latest
test_dataset:
  desc: null
  value: test_data.csv:latest
