wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.2
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683665833.614858
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 23
      4: 3.10.10
      5: 0.15.2
      8:
      - 5
trainval_artifact:
  desc: null
  value: trainval_data.csv:latest
val_size:
  desc: null
  value: 0.2
random_seed:
  desc: null
  value: 42
xgb_config:
  desc: null
  value: /home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/outputs/2023-05-09/21-57-04/config.yaml
output_artifact:
  desc: null
  value: xgboost_export
n_estimators:
  desc: null
  value: 100
max_depth:
  desc: null
  value: 15
min_samples_split:
  desc: null
  value: 4
min_samples_leaf:
  desc: null
  value: 3
n_jobs:
  desc: null
  value: -1
criterion:
  desc: null
  value: mae
max_features:
  desc: null
  value: 0.5
oob_score:
  desc: null
  value: true
