wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683112416.298409
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.10.8
      5: 0.15.1
      8:
      - 1
      - 5
    session_history: code/_session_history.ipynb
