name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.1
  - pip=22.0.4
  - mlflow=1.23.0
  - scikit-learn=1.0.2
  - pip:
      - wandb
      - xgboost==1.7.5
