wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.2
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685441075.008738
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 23
      4: 3.10.11
      5: 0.15.2
      8:
      - 5
mlflow_model:
  desc: null
  value: xgboost_export:prod
test_dataset:
  desc: null
  value: test_data.csv:latest
