wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.2
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685540549.329153
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.10
      5: 0.15.2
      8:
      - 5
trainval_artifact:
  desc: null
  value: trainval_data.csv:latest
val_size:
  desc: null
  value: 0.2
model_config:
  desc: null
  value: /home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/outputs/2023-05-31/14-40-57/config.yaml
output_artifact:
  desc: null
  value: model_export
fit_intercept:
  desc: null
  value: true
copy_X:
  desc: null
  value: true
normalize:
  desc: null
  value: true
positive:
  desc: null
  value: false
