wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685713460.874499
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.10.11
      5: 0.15.3
      8:
      - 5
step_description:
  desc: null
  value: This step checks if the previous tour predictions were correct and predicts
    the result of the next tour matches
