name: tour_eval_pred
channels:
  - conda-forge
  - defaults
dependencies:
  - selenium=4.8.3
  - mlflow=1.23.0
  - numpy=1.22.3
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - pandas=1.4.1
  - pip=22.0.4
  - pip:
      - wandb
